# Generated by Django 4.1.3 on 2022-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_balance_borrower_alter_balance_lender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='balance',
            name='expiration',
            field=models.BigIntegerField(default=1667647398),
            preserve_default=False,
        ),
    ]
